[build]
  base = "web/"
  command = "npm run build"
  ignore = "[[ -z $CACHED_COMMIT_REF ]] && git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."

[[redirects]]
  from = "/bee.js"
  to = "https://cdn.splitbee.io/sb.js"
  status = 200

  from = "/_hive/*"
  to = "https://hive.splitbee.io/:splat"
  status = "200"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "text/xml"
