[build]
  base = "web/"
  command = "npm run build"
  ignore = "[[ -z $CACHED_COMMIT_REF ]] && git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."


[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "text/xml"
