[build]
  base = "web/"
  publish = "dist"
  command = "npm run build"
  ignore = "[[ -z $CACHED_COMMIT_REF ]] && git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."

 [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "text/xml"
